on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v6

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        protocol: ftps
        port: ${{ secrets.PORT }}
        server-dir: ${{ secrets.SERVER_DIR }}
